// !!! This is a file automatically generated by hipify!!!
#ifndef INCLUDE_GUARD_CUDA_CUPY_CUDA_RUNTIME_H
#define INCLUDE_GUARD_CUDA_CUPY_CUDA_RUNTIME_H

#include <hip/hip_runtime.h>  // for TORCH_HIP_VERSION
#include <hip/hip_runtime.h>

extern "C" {

bool hip_environment = false;

#if TORCH_HIP_VERSION < 10010
const int cudaErrorContextIsDestroyed = 709;
#endif

#if TORCH_HIP_VERSION < 11010
// APIs added in CUDA 11.1
hipError_t cudaGraphUpload(...) {
    return hipErrorUnknown;
}
#endif

#if TORCH_HIP_VERSION < 11020
// APIs added in CUDA 11.2
typedef void* cudaMemPool_t;
enum cudaMemPoolAttr {};
enum cudaMemAllocationType {};
enum cudaMemAllocationHandleType {};
enum cudaMemLocationType {};
struct cudaMemLocation {
    int id;
    cudaMemLocationType type;
};
struct cudaMemPoolProps {
    cudaMemAllocationType allocType;
    cudaMemAllocationHandleType handleTypes;
    struct cudaMemLocation location;
    unsigned char reserved[64];
    void* win32SecurityAttributes;
};

hipError_t cudaMallocAsync(...) {
    return hipErrorUnknown;
}

hipError_t cudaMallocFromPoolAsync(...) {
    return hipErrorUnknown;
}

hipError_t cudaFreeAsync(...) {
    return hipErrorUnknown;
}

hipError_t cudaDeviceSetMemPool(...) {
    return hipErrorUnknown;
}

hipError_t cudaDeviceGetDefaultMemPool(...) {
    return hipErrorUnknown;
}

hipError_t cudaDeviceGetMemPool(...) {
    return hipErrorUnknown;
}

hipError_t cudaMemPoolCreate(...) {
    return hipErrorUnknown;
}

hipError_t cudaMemPoolDestroy(...) {
    return hipErrorUnknown;
}

hipError_t cudaMemPoolTrimTo(...) {
    return hipErrorUnknown;
}

hipError_t cudaMemPoolSetAttribute(...) {
    return hipErrorUnknown;
}

hipError_t cudaMemPoolGetAttribute(...) {
    return hipErrorUnknown;
}

#endif

} // extern "C"

#endif // #ifndef INCLUDE_GUARD_CUDA_CUPY_CUDA_RUNTIME_H
