// !!! This is a file automatically generated by hipify!!!
#ifndef INCLUDE_GUARD_CUDA_CUPY_PROFILER_H
#define INCLUDE_GUARD_CUDA_CUPY_PROFILER_H

#include <hip/hip_runtime.h>
#include <hip/hip_runtime_api.h>

#if TORCH_HIP_VERSION >= 12000
// Functions removed in CUDA 12.0

enum cudaOutputMode_t {};

hipError_t hipProfilerInitialize(...) {
    return hipErrorUnknown;
}

#endif // #if TORCH_HIP_VERSION >= 12

#endif // #ifndef INCLUDE_GUARD_CUDA_CUPY_PROFILER_H
