// !!! This is a file automatically generated by hipify!!!
#ifndef INCLUDE_GUARD_CUDA_CUPY_CUBLAS_H
#define INCLUDE_GUARD_CUDA_CUPY_CUBLAS_H

#include <hip/hip_runtime.h>
#include <rocblas.h>

#if TORCH_HIP_VERSION >= 11000

#define cublasGemmEx_v11 rocblas_gemmex
#define cublasGemmStridedBatchedEx_v11 cublasGemmStridedBatchedEx

#else

typedef enum{} cublasComputeType_t;
rocblas_status cublasGemmEx_v11(...) {
    return rocblas_status_not_implemented;
}
rocblas_status cublasGemmStridedBatchedEx_v11(...) {
    return rocblas_status_not_implemented;
}

#endif // if TORCH_HIP_VERSION >= 11000

#endif // #ifndef INCLUDE_GUARD_CUDA_CUPY_CUBLAS_H
