// !!! This is a file automatically generated by hipify!!!
#ifndef INCLUDE_GUARD_CUDA_CUPY_CUDA_H
#define INCLUDE_GUARD_CUDA_CUPY_CUDA_H

#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>

#endif // #ifndef INCLUDE_GUARD_CUDA_CUPY_CUDA_H
