// !!! This is a file automatically generated by hipify!!!
#ifndef INCLUDE_GUARD_CUDA_CUPY_NVRTC_H
#define INCLUDE_GUARD_CUDA_CUPY_NVRTC_H

#include <hip/hip_runtime.h>  // for TORCH_HIP_VERSION
#include <hip/hiprtc.h>

extern "C" {

#if TORCH_HIP_VERSION < 11010
// functions added in CUDA 11.1
hiprtcResult nvrtcGetCUBINSize(...) {
    return HIPRTC_ERROR_COMPILATION;
}

hiprtcResult nvrtcGetCUBIN(...) {
    return HIPRTC_ERROR_COMPILATION;
}
#endif

}

#endif // #ifndef INCLUDE_GUARD_CUDA_CUPY_NVRTC_H
