name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  static-checks:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Checkout using commit hash to make "no-commit-to-branch" test pass.
        ref: ${{ github.sha }}

    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.9'

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key:
          static-checks-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys:
          static-checks-

    - name: Setup pre-commit
      run: |
        pip install pre-commit

    - name: Check
      run: |
        pre-commit run -a --show-diff-on-failure

  build-cuda:
    runs-on: ubuntu-22.04
    env:
      CUPY_CI: GitHub

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: build-cuda-${{ github.sha }}
        restore-keys: |
          build-cuda-${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          build-cuda-

    - name: Setup ccache
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ccache
        echo "PATH=/usr/lib/ccache:${PATH}" >> "${GITHUB_ENV}"
        ccache --show-stats -v

    - name: Build
      run: |
        pip install -U pip wheel
        pip install cython
        READTHEDOCS=True pip install -v -e .
        ccache --max-size 0.5Gi --cleanup --show-stats

    - name: Docs Build
      run: |
        # Test to detect invalid escape sequences in docstrings (#1619)
        python -Werror::DeprecationWarning -m compileall -f -q cupy cupyx examples tests docs
        pushd docs
        pip install -r requirements.txt
        SPHINXOPTS="-W --keep-going -j 4" make html
        popd

  build-rocm:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build & Test
      run: |
        docker run --rm -v "${PWD}:/src" -w /src "rocm/dev-ubuntu-20.04:5.0-complete" bash .github/workflows/pretest-rocm-test.sh
